apiVersion: apps/v1
kind: Deployment
metadata:
  name: tetris
  labels:
    demo: nv
spec:
  selector:
    matchLabels:
      app: nv
      tier: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: nv
        tier: demo
    spec:
      containers:
      - name: tetris
        image: 	cacrawford/tetris
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tetris-loadbalancer-service
spec:
  type: LoadBalancer
  selector:
    app: fleet
    tier: demo
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30051
