apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
   replicas: {{ .Values.replicas }}
  template:
    spec:
      containers:
      - name: scale-demo
        image: monachus/rancher-demo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
