apiVersion: apps/v1
kind: Deployment
metadata:
  name: scale
spec:
  selector:
    matchLabels:
      app: fleet
      tier: demo
  replicas: 2
  template:
    metadata:
      labels:
        app: fleet
        tier: demo
    spec:
      containers:
      - name: scale
        image: 	monachus/rancher-demo
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
